# Generated by Django 5.2.1 on 2025-05-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_alter_job_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='icon',
            field=models.ImageField(upload_to='icons/'),
        ),
    ]
