# Generated by Django 5.2.1 on 2025-05-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProjects', '0005_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='shortDescription',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
