# Generated by Django 5.2.1 on 2025-07-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyProjects', '0007_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
